# Usar a imagem base CentOS 7
FROM centos:7

# Instalar wget e Java
RUN yum install -y wget java-1.8.0-openjdk-devel

# Transferir e instalar o Tomcat
ENV TOMCAT_VERSION=8.5.64
ENV TOMCAT_HOME=/opt/tomcat
ENV JAVA_HOME=/usr/lib/jvm/java-openjdk
ENV CATALINA_HOME=/opt/tomcat
RUN wget --no-check-certificate "https://archive.apache.org/dist/tomcat/tomcat-8/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz" -O /tmp/tomcat.tar.gz && \
    tar xzf /tmp/tomcat.tar.gz -C /opt && \
    ln -s /opt/apache-tomcat-${TOMCAT_VERSION} $TOMCAT_HOME && \
    rm /tmp/tomcat.tar.gz

# Copiar o arquivo WAR para o /webapps do Tomcat
COPY sample.war $TOMCAT_HOME/webapps/

# Copiar o keystore gerado para o Tomcat
COPY keystore.jks /opt/apache-tomcat-${TOMCAT_VERSION}/

# Verificar se o keystore foi copiado corretamente
RUN ls -l /opt/apache-tomcat-${TOMCAT_VERSION}/keystore.jks

# Copiar o arquivo server.xml com as configurações SSL/TLS
COPY server.xml /opt/apache-tomcat-${TOMCAT_VERSION}/conf/server.xml

# Expor a porta 4041
EXPOSE 4041

# Iniciar o Tomcat
CMD ["/opt/tomcat/bin/catalina.sh", "run"]